//! Stylesheet generation.
//!
//! The dock's CSS is produced at runtime from the active Omarchy palette plus
//! the theme's `shell.toml` tokens and the user's config, then handed to a
//! single `GtkCssProvider` that is swapped wholesale on every theme or config
//! change. Swapping one provider (rather than adding more) is what keeps live
//! reload from leaking styles.
//!
//! Two visual languages are supported. `Style::Omarchy` draws the dock the way
//! the Omarchy shell draws its own surfaces — the same background alpha, the
//! same hover fill, the same border gradient, the same corner radius — so the
//! dock, the bar and the menu read as one program. `Style::Glass` keeps the
//! translucent rounded slab a dock traditionally has.

use super::shell::{Border, Shell, Surface};
use super::{Palette, Rgb};
use crate::config::{self, Config, Style};

/// Border width below which GTK renders nothing at all. A theme asking for a
/// hairline should still get one.
const MIN_BORDER_PX: f64 = 1.0;

/// Build the full stylesheet: palette variables, dock chrome, then user CSS.
pub fn generate(cfg: &Config, palette: &Palette, shell: &Shell) -> String {
    let mut s = String::with_capacity(8192);
    let omarchy = cfg.theme.style == Style::Omarchy;

    s.push_str("/* generated by omarchy-dock — do not edit; see style.css */\n");
    s.push_str(&format!(
        "/* theme: {} ({}), style: {} */\n",
        palette.name,
        if palette.is_dark() { "dark" } else { "light" },
        if omarchy { "omarchy" } else { "glass" },
    ));

    // ── palette variables ───────────────────────────────────────────────────
    // Exposed so user CSS can reference the live theme, e.g. @omarchy_accent.
    let mut names: Vec<_> = palette.iter().collect();
    names.sort_by(|a, b| a.0.cmp(b.0));
    for (name, rgb) in names {
        s.push_str(&format!("@define-color omarchy_{name} {};\n", rgb.to_css()));
    }

    let accent = palette.accent();
    let urgent = palette.urgent();

    // In the Omarchy style every colour comes from the shell tokens, so the
    // dock cannot drift from the bar. In glass it comes from the palette.
    let (panel, fg) = if omarchy {
        (shell.popups.clone(), shell.popups.text)
    } else {
        (
            Surface {
                background: palette.background(),
                background_alpha: cfg.theme.opacity,
                text: palette.foreground(),
                border: Border::solid(hairline_color(palette)),
                border_alpha: 1.0,
                border_width: 1.0,
            },
            palette.foreground(),
        )
    };

    let radius = radius(cfg, omarchy);
    let ctl = &shell.controls;
    let m = &shell.metrics;

    // Interaction fills, straight from `[controls]`. Every Omarchy control
    // paints these exact alphas, so a dock row highlights identically to a
    // bar widget or a menu row.
    let hover_fill = ctl.color.with_alpha(ctl.hover_fill_alpha);
    let selected_fill = ctl.color.with_alpha(ctl.selected_fill_alpha);
    let pressed_fill = ctl.color.with_alpha(ctl.pressed_fill_alpha);

    s.push_str(&format!("@define-color dock_bg {};\n", panel.background_css()));
    s.push_str(&format!("@define-color dock_fg {};\n", fg.to_css()));
    s.push_str(&format!("@define-color dock_accent {};\n", accent.to_css()));
    s.push_str(&format!("@define-color dock_urgent {};\n", urgent.to_css()));
    s.push_str(&format!("@define-color dock_hover {hover_fill};\n"));
    s.push_str(&format!("@define-color dock_selected {selected_fill};\n"));

    // ── dock chrome ─────────────────────────────────────────────────────────
    // The layer surface itself must stay fully transparent: Hyprland blurs
    // whatever the surface covers, so a window-level background would be
    // blurred edge-to-edge and the rounded corners would be lost.
    s.push_str(
        "\nwindow, window.background { background: transparent; box-shadow: none; }\n",
    );

    // Glass earns a drop shadow because it floats; an Omarchy surface does not
    // have one anywhere else in the desktop, so it must not have one here.
    let shadow = if omarchy {
        "none".to_string()
    } else {
        let a = if palette.is_dark() { 0.45 } else { 0.20 };
        format!("0 8px 28px rgba(0, 0, 0, {a:.2})")
    };

    s.push_str(&format!(
        "\n.dock-panel {{
  background-color: @dock_bg;
{border}
  border-radius: {radius}px;
  box-shadow: {shadow};
}}\n",
        border = border_rules(&panel.border, panel.border_alpha, panel.border_width, 2),
    ));

    // ── items ───────────────────────────────────────────────────────────────
    // The hover plate is the shell's own control treatment applied to a dock
    // slot: it sits *behind* the icon so a magnified icon still grows over it.
    s.push_str(&format!(
        "
.dock-hover-plate {{
  background-color: @dock_hover;
  border-radius: {plate_radius}px;
{plate_border}
}}

.dock-indicator {{
  background-color: @dock_accent;
  border-radius: 2px;
  min-width: 5px;
  min-height: 3px;
}}

.dock-indicator.urgent {{ background-color: @dock_urgent; }}

/* Focused app's indicator is brighter and wider than a merely running one, so
   'which window will this click reach' is readable at a glance. */
.dock-indicator.active {{
  background-color: @dock_fg;
  min-width: 10px;
}}

.dock-badge {{
  background-color: @dock_urgent;
  color: {badge_fg};
  border-radius: {badge_radius}px;
  font-size: {caption}px;
  font-weight: bold;
  padding: 0 {badge_pad}px;
}}

/* The dock's own furniture — launcher, folders, Trash — drawn as monochrome
   glyphs in the theme foreground, the way every bar widget is drawn. Only
   real application icons carry colour. */
.dock-glyph {{
  color: @dock_fg;
  font-family: \"omarchy\", \"JetBrainsMono Nerd Font\", \"Symbols Nerd Font\", monospace;
}}

.dock-label {{
  color: @dock_fg;
  font-size: {body}px;
}}

/* Workspace tiles, drawn the way the bar's workspace widget draws them: a
   number that is dim when the workspace is empty, bright when it holds
   windows, and filled when it is the one you are on. The three states are the
   [controls] fills, so they match every other Omarchy control exactly. */
.dock-workspace {{
  color: @dock_fg;
  opacity: 0.35;
  border-radius: {ws_radius}px;
  background-color: {ws_idle};
  font-family: \"JetBrainsMono Nerd Font\", monospace;
}}

.dock-workspace.occupied {{ opacity: 0.75; }}

.dock-workspace.current {{
  opacity: 1;
  background-color: @dock_selected;
}}
",
        // Badge text must contrast with the urgency colour, not the panel.
        badge_fg = if urgent.luminance() > 0.45 { "#000000" } else { "#ffffff" },
        badge_radius = if omarchy { (radius * 0.4).max(2.0) } else { 9.0 },
        badge_pad = m.space("xs", 3.0).max(3.0),
        caption = m.font("caption", 0.833),
        body = m.font("body", 1.0),
        plate_radius = if omarchy { (radius * 0.6).max(2.0) } else { 10.0 },
        ws_radius = if omarchy { (radius * 0.6).max(2.0) } else { 8.0 },
        ws_idle = ctl.color.with_alpha(ctl.normal_fill_alpha),
        plate_border = border_rules(
            &Border::solid(ctl.color),
            ctl.hover_border_alpha,
            if omarchy { ctl.hover_border_width } else { 0.0 },
            0,
        ),
    ));

    // ── popovers: menus, stacks, settings ───────────────────────────────────
    // These are the surfaces most visibly shared with the shell, so they take
    // the `[menu]` tokens directly — including the selected-row treatment,
    // which is a fill *and* a hairline, not just a fill.
    let menu = if omarchy {
        shell.menu.surface.clone()
    } else {
        Surface { border: Border::solid(hairline_color(palette)), ..panel.clone() }
    };
    let (sel_bg, sel_alpha) = if omarchy {
        (shell.menu.selected_background, shell.menu.selected_background_alpha)
    } else {
        (accent, 0.28)
    };

    s.push_str(&format!(
        "
.dock-menu > contents {{
  background-color: {menu_bg};
{menu_border}
  border-radius: {radius}px;
  padding: {pad}px;
}}

.dock-menu-list {{ min-width: {menu_w}px; }}

.dock-menu-item {{
  padding: {row_y}px {row_x}px;
  border-radius: {row_radius}px;
  color: {menu_fg};
  font-size: {body}px;
  background: transparent;
}}

.dock-menu-item:hover {{
  background-color: {sel_fill};
{sel_border}
}}

.dock-menu-item:active {{ background-color: {pressed_fill}; }}

.dock-menu-heading {{
  padding: {row_y}px {row_x}px 2px {row_x}px;
  font-size: {caption}px;
  opacity: 0.6;
  color: {menu_fg};
}}

.dock-menu-sep {{
  margin: {gap}px {pad}px;
  background-color: {divider};
}}
",
        menu_bg = menu.background_css(),
        menu_fg = menu.text.to_css(),
        menu_border = border_rules(&menu.border, menu.border_alpha, menu.border_width, 2),
        menu_w = m.space("dropdown-width", 240.0).max(190.0),
        pad = m.space("popup-padding", 6.0).max(4.0),
        row_x = m.space("row-padding-x", 12.0).max(8.0),
        row_y = m.space("control-padding-y", 6.0).max(4.0),
        row_radius = if omarchy { (radius * 0.6).max(2.0) } else { 7.0 },
        gap = m.space("sm", 4.0),
        body = m.font("body", 1.0),
        caption = m.font("caption", 0.833),
        sel_fill = sel_bg.with_alpha(sel_alpha),
        sel_border = border_rules(
            &shell.menu.selected_border,
            if omarchy { shell.menu.selected_border_alpha } else { 0.0 },
            if omarchy { ctl.normal_border_width } else { 0.0 },
            0,
        ),
        divider = fg.with_alpha(0.18),
    ));

    // ── tooltip, separator, stacks, settings ────────────────────────────────
    let tip = if omarchy {
        shell.tooltip.clone()
    } else {
        // Glass: the label floats over the desktop, not the panel, so it needs
        // to be more opaque than the slab or it is unreadable on a busy
        // wallpaper.
        Surface {
            background_alpha: (cfg.theme.opacity + 0.32).min(0.96),
            ..panel.clone()
        }
    };

    s.push_str(&format!(
        "
/* GTK draws its own highlight on a widget that is an active drop target — an
   accent-coloured outline. The dock shows the drop position by opening a gap
   between icons instead, so suppress it. */
*:drop(active) {{
  outline: none;
  box-shadow: none;
  border-color: transparent;
  background-image: none;
}}

/* Divider between dock sections. Derived from the foreground, not the panel
   hairline: at hairline alpha it is invisible on dark themes, which defeats
   the point of a divider. */
.dock-separator {{
  background-color: {divider};
  border-radius: 1px;
  /* A childless widget takes its size from CSS, so min-* is what actually
     gives the divider an allocation to paint into. */
  min-width: 2px;
  min-height: {sep_len}px;
}}

/* Name of the hovered icon, drawn in the reserved band above the panel. */
.dock-tip-label {{
  background-color: {tip_bg};
  color: {tip_fg};
{tip_border}
  border-radius: {tip_radius}px;
  padding: {tip_y}px {tip_x}px;
  font-size: {body}px;
}}

.dock-stack {{ min-width: {stack_w}px; }}

.dock-stack-row {{ padding: 0 {gap}px; }}

.dock-stack-action {{
  padding: {gap}px;
  border-radius: {row_radius}px;
  color: {menu_fg};
  opacity: 0.65;
  background: transparent;
}}

.dock-stack-action:hover {{
  opacity: 1;
  background-color: {sel_fill};
}}

.dock-settings {{ min-width: {settings_w}px; }}

/* The settings window is a real toplevel, not a layer surface, so unlike the
   dock it does want an opaque background of its own. */
.dock-settings-window,
.dock-settings-window > * {{
  background-color: {menu_bg};
  color: {menu_fg};
}}

/* GTK's default switch accent is its own blue, which is the one thing in the
   window that does not come from the theme. */
.dock-settings-window switch:checked {{
  background-color: @dock_accent;
}}

.dock-settings-note {{
  color: {menu_fg};
  opacity: 0.55;
  font-size: {caption}px;
  padding: 0 {row_x}px {gap}px {row_x}px;
}}

.dock-settings-row {{ padding: 2px {row_x}px; }}

.dock-settings-row label {{
  color: {menu_fg};
  font-size: {body}px;
}}
",
        divider = fg.with_alpha(0.34),
        sep_len = (cfg.dock.icon_size * 0.58).round(),
        tip_bg = tip.background_css(),
        tip_fg = tip.text.to_css(),
        tip_border = border_rules(&tip.border, tip.border_alpha, tip.border_width, 2),
        tip_radius = if omarchy { (radius * 0.6).max(2.0) } else { 7.0 },
        tip_x = m.space("control-padding-x", 10.0).max(6.0),
        tip_y = m.space("xxs", 2.0).max(2.0),
        body = m.font("body", 1.0),
        gap = m.space("sm", 4.0),
        row_x = m.space("row-padding-x", 12.0).max(8.0),
        row_radius = if omarchy { (radius * 0.6).max(2.0) } else { 6.0 },
        menu_fg = menu.text.to_css(),
        sel_fill = sel_bg.with_alpha(sel_alpha),
        stack_w = m.space("searchable-dropdown-width", 260.0).max(220.0),
        settings_w = m.space("searchable-dropdown-width", 270.0).max(240.0),
        menu_bg = menu.background_css(),
        caption = m.font("caption", 0.833),
    ));

    // ── user overrides ──────────────────────────────────────────────────────
    let user = config::expand_tilde(&cfg.theme.user_css);
    match std::fs::read_to_string(&user) {
        Ok(text) => {
            s.push_str("\n/* ── user style.css ── */\n");
            s.push_str(&text);
            tracing::debug!(path = %user.display(), "user CSS applied");
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => tracing::warn!(path = %user.display(), error = %e, "cannot read user CSS"),
    }

    s
}

/// Corner radius for the current style.
///
/// The Omarchy shell mirrors Hyprland's `decoration:rounding` for every
/// surface it draws, so a dock that picks its own radius is immediately the
/// odd one out — including for users who set rounding to 0.
pub fn radius(cfg: &Config, omarchy: bool) -> f64 {
    if let Some(r) = cfg.theme.radius {
        return r;
    }
    if omarchy {
        super::hyprland_rounding().unwrap_or(6.0)
    } else {
        cfg.dock.radius
    }
}

/// Border declarations for a surface, gradient-aware.
///
/// GTK cannot put a gradient in `border-color`, but it does support
/// `border-image`, which is how Omarchy's active-border gradient survives the
/// trip into GTK CSS. A flat border takes the plain path so the radius is not
/// lost: `border-image` ignores `border-radius`, which is fine for a hairline
/// on a barely-rounded Omarchy surface but wrong for a glass slab.
///
/// `slice` is the `border-image-slice` value; 0 for widgets whose corners are
/// too round to fake.
fn border_rules(border: &Border, alpha: f64, width: f64, slice: u32) -> String {
    // Test the requested width, not the rounded one: a theme asking for a
    // hairline thinner than a pixel wants a hairline, not nothing. Only an
    // explicit zero means no border.
    if alpha <= 0.0 || width <= 0.0 {
        return "  border: none;".into();
    }
    let width = width.max(MIN_BORDER_PX).round();

    if border.is_gradient() && slice > 0 {
        format!(
            "  border: {width}px solid transparent;\n  \
             border-image-source: {src};\n  \
             border-image-slice: {slice};\n  \
             border-image-width: {width}px;",
            src = border.to_css_gradient(alpha),
        )
    } else {
        format!("  border: {width}px solid {};", border.to_css_solid(alpha))
    }
}

/// Hairline for the glass style, which has no shell tokens to draw on.
fn hairline_color(palette: &Palette) -> Rgb {
    if palette.is_dark() {
        Rgb { r: 255, g: 255, b: 255 }
    } else {
        palette.background().mix(Rgb { r: 0, g: 0, b: 0 }, 0.35)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme::shell::Shell;

    fn setup(style: Style) -> (Config, Palette, Shell) {
        let mut cfg = Config::default();
        cfg.theme.style = style;
        // Pin the radius so the tests do not depend on a running Hyprland.
        cfg.theme.radius = Some(6.0);
        let palette = Palette::default();
        let shell = Shell::fallback(&palette);
        (cfg, palette, shell)
    }

    #[test]
    fn a_gradient_border_becomes_a_border_image() {
        let border = Border {
            stops: vec![
                (Rgb { r: 0x79, g: 0x81, b: 0x86 }, 0.93),
                (Rgb { r: 0xca, g: 0xcc, b: 0xcc }, 0.93),
            ],
            angle: 45.0,
        };
        let css = border_rules(&border, 1.0, 1.0, 2);
        assert!(css.contains("border-image-source: linear-gradient(45deg"));
        assert!(css.contains("border-image-slice: 2"));
        // A gradient cannot go in border-color, so the border itself is clear.
        assert!(css.contains("border: 1px solid transparent"));
    }

    #[test]
    fn a_gradient_flattens_where_border_image_would_lose_the_radius() {
        let border = Border {
            stops: vec![
                (Rgb { r: 0, g: 0, b: 0 }, 1.0),
                (Rgb { r: 255, g: 255, b: 255 }, 1.0),
            ],
            angle: 0.0,
        };
        // slice 0 means "this widget is too round for border-image".
        let css = border_rules(&border, 1.0, 1.0, 0);
        assert!(!css.contains("border-image"));
        assert!(css.contains("#808080") || css.contains("128, 128, 128"));
    }

    #[test]
    fn a_zero_width_or_transparent_border_is_omitted_entirely() {
        let b = Border::solid(Rgb { r: 1, g: 2, b: 3 });
        assert_eq!(border_rules(&b, 1.0, 0.0, 2), "  border: none;");
        assert_eq!(border_rules(&b, 0.0, 1.0, 2), "  border: none;");
    }

    #[test]
    fn a_sub_pixel_border_is_still_drawn() {
        // A theme asking for a hairline must not get nothing: GTK renders no
        // border at all below 1px.
        let b = Border::solid(Rgb { r: 1, g: 2, b: 3 });
        let css = border_rules(&b, 1.0, 0.4, 2);
        assert!(css.contains("1px solid"), "{css}");
    }

    #[test]
    fn the_omarchy_style_takes_its_opacity_from_the_theme_not_the_config() {
        let (mut cfg, palette, mut shell) = setup(Style::Omarchy);
        // Config says half-transparent; the theme says fully opaque.
        cfg.theme.opacity = 0.5;
        shell.popups.background_alpha = 1.0;
        let css = generate(&cfg, &palette, &shell);
        assert!(css.contains("@define-color dock_bg rgba(20, 21, 30, 1.000)"), "{}",
            first_lines(&css, 40));

        // Glass honours the config instead.
        let (mut cfg, palette, shell) = setup(Style::Glass);
        cfg.theme.opacity = 0.5;
        let css = generate(&cfg, &palette, &shell);
        assert!(css.contains("@define-color dock_bg rgba(20, 21, 30, 0.500)"));
    }

    #[test]
    fn the_omarchy_style_has_no_drop_shadow() {
        let (cfg, palette, shell) = setup(Style::Omarchy);
        let css = generate(&cfg, &palette, &shell);
        assert!(css.contains("box-shadow: none"));
        assert!(!css.contains("box-shadow: 0 8px"));

        let (cfg, palette, shell) = setup(Style::Glass);
        let css = generate(&cfg, &palette, &shell);
        assert!(css.contains("box-shadow: 0 8px"));
    }

    #[test]
    fn hover_and_selected_fills_come_from_the_control_tokens() {
        let (cfg, palette, mut shell) = setup(Style::Omarchy);
        shell.controls.hover_fill_alpha = 0.08;
        shell.controls.selected_fill_alpha = 0.18;
        let css = generate(&cfg, &palette, &shell);
        assert!(css.contains("@define-color dock_hover rgba(200, 204, 212, 0.080)"), "{}",
            first_lines(&css, 40));
        assert!(css.contains("@define-color dock_selected rgba(200, 204, 212, 0.180)"));
    }

    #[test]
    fn the_shell_scale_drives_the_type_and_spacing_of_dock_surfaces() {
        let (cfg, palette, mut shell) = setup(Style::Omarchy);
        let small = generate(&cfg, &palette, &shell);
        assert!(small.contains("font-size: 12px"));

        // Doubling the shell's base size must double the dock's type, the way
        // `omarchy display text size` doubles the bar's.
        shell.metrics.font_base_size = 24.0;
        let large = generate(&cfg, &palette, &shell);
        assert!(large.contains("font-size: 24px"), "{}", first_lines(&large, 200));
        assert!(!large.contains("font-size: 12px"));
    }

    #[test]
    fn an_explicit_radius_overrides_both_styles() {
        let mut cfg = Config::default();
        cfg.theme.radius = Some(17.0);
        assert_eq!(radius(&cfg, true), 17.0);
        assert_eq!(radius(&cfg, false), 17.0);
    }

    fn first_lines(s: &str, n: usize) -> String {
        s.lines().take(n).collect::<Vec<_>>().join("\n")
    }
}
