//! Stylesheet generation.
//!
//! The dock's CSS is produced at runtime from the active Omarchy palette plus
//! the user's config, then handed to a single `GtkCssProvider` that is swapped
//! wholesale on every theme or config change. Swapping one provider (rather
//! than adding more) is what keeps live reload from leaking styles.

use super::{Palette, Rgb};
use crate::config::{self, Config};

/// Build the full stylesheet: palette variables, dock chrome, then user CSS.
pub fn generate(cfg: &Config, palette: &Palette) -> String {
    let mut s = String::with_capacity(4096);

    s.push_str("/* generated by omarchy-dock — do not edit; see style.css */\n");
    s.push_str(&format!(
        "/* theme: {} ({}) */\n",
        palette.name,
        if palette.is_dark() { "dark" } else { "light" }
    ));

    // ── palette variables ───────────────────────────────────────────────────
    // Exposed so user CSS can reference the live theme, e.g. @omarchy_accent.
    let mut names: Vec<_> = palette.iter().collect();
    names.sort_by(|a, b| a.0.cmp(b.0));
    for (name, rgb) in names {
        s.push_str(&format!("@define-color omarchy_{name} {};\n", rgb.to_css()));
    }

    let bg = palette.background();
    let fg = palette.foreground();
    let accent = palette.accent();
    let urgent = palette.urgent();

    // Hairline and shadow have to move in opposite directions depending on
    // whether the panel is dark or light, or one of them vanishes.
    // Dividers need to read against the panel in both polarities.
    let divider = fg.with_alpha(0.34);
    // The label floats over the desktop, not the panel, so it needs to be more
    // opaque than the glass or it is unreadable against a busy wallpaper.
    let tip_bg = bg.with_alpha((cfg.theme.opacity + 0.32).min(0.96));

    let (hairline, shadow_alpha) = if palette.is_dark() {
        (Rgb { r: 255, g: 255, b: 255 }.with_alpha(0.10), 0.45)
    } else {
        (bg.mix(Rgb { r: 0, g: 0, b: 0 }, 0.35).with_alpha(0.18), 0.20)
    };

    s.push_str(&format!("@define-color dock_bg {};\n", bg.with_alpha(cfg.theme.opacity)));
    s.push_str(&format!("@define-color dock_fg {};\n", fg.to_css()));
    s.push_str(&format!("@define-color dock_accent {};\n", accent.to_css()));
    s.push_str(&format!("@define-color dock_urgent {};\n", urgent.to_css()));

    // ── dock chrome ─────────────────────────────────────────────────────────
    // The layer surface itself must stay fully transparent: Hyprland blurs
    // whatever the surface covers, so a window-level background would be
    // blurred edge-to-edge and the rounded corners would be lost.
    s.push_str(
        "\nwindow, window.background { background: transparent; box-shadow: none; }\n",
    );

    s.push_str(&format!(
        "\n.dock-panel {{
  background-color: @dock_bg;
  border: 1px solid {hairline};
  border-radius: {radius}px;
  box-shadow: 0 8px 28px rgba(0, 0, 0, {shadow_alpha:.2});
}}\n",
        radius = cfg.dock.radius,
    ));

    // Running/urgency indicators and window-count badges.
    s.push_str(&format!(
        "
.dock-indicator {{
  background-color: @dock_accent;
  border-radius: 2px;
  min-width: 5px;
  min-height: 3px;
}}

.dock-indicator.urgent {{ background-color: @dock_urgent; }}

.dock-badge {{
  background-color: @dock_urgent;
  color: {badge_fg};
  border-radius: 9px;
  font-size: 10px;
  font-weight: bold;
  padding: 0 5px;
}}

.dock-label {{
  color: @dock_fg;
  font-size: 12px;
}}
",
        // Badge text must contrast with the urgency colour, not the panel.
        badge_fg = if urgent.luminance() > 0.45 { "#000000" } else { "#ffffff" },
    ));

    // Section dividers, context menu, and the settings panel.
    s.push_str(&format!(
        "
/* Focused app's indicator is brighter and wider than a merely running one, so
   'which window will this click reach' is readable at a glance. */
.dock-indicator.active {{
  background-color: @dock_fg;
  min-width: 10px;
}}

/* GTK draws its own highlight on a widget that is an active drop target — an
   accent-coloured outline. The dock shows the drop position by opening a gap
   between icons instead, so suppress it. */
*:drop(active) {{
  outline: none;
  box-shadow: none;
  border-color: transparent;
  background-image: none;
}}

/* Divider between dock sections. Derived from the foreground, not the panel
   hairline: at hairline alpha it is invisible on dark themes, which defeats
   the point of a divider. */
.dock-separator {{
  background-color: {divider};
  border-radius: 1px;
  /* A childless widget takes its size from CSS, so min-* is what actually
     gives the divider an allocation to paint into. */
  min-width: 2px;
  min-height: 26px;
}}

.dock-menu > contents {{
  background-color: @dock_bg;
  border: 1px solid {hairline};
  border-radius: 12px;
  padding: 4px;
}}

.dock-menu-list {{ min-width: 190px; }}

.dock-menu-item {{
  padding: 6px 10px;
  border-radius: 7px;
  color: @dock_fg;
  background: transparent;
}}

.dock-menu-item:hover {{ background-color: {accent_soft}; }}

.dock-menu-heading {{
  padding: 6px 10px 2px 10px;
  font-size: 11px;
  opacity: 0.6;
  color: @dock_fg;
}}

.dock-menu-sep {{
  margin: 4px 6px;
  background-color: {hairline};
}}

/* Name of the hovered icon, drawn in the reserved band above the panel. */
.dock-tip-label {{
  background-color: {tip_bg};
  color: @dock_fg;
  border: 1px solid {hairline};
  border-radius: 7px;
  padding: 2px 8px;
  font-size: 12px;
}}

.dock-stack {{ min-width: 260px; }}

.dock-stack-row {{ padding: 0 4px; }}

.dock-stack-action {{
  padding: 4px;
  border-radius: 6px;
  color: @dock_fg;
  opacity: 0.65;
  background: transparent;
}}

.dock-stack-action:hover {{
  opacity: 1;
  background-color: {accent_soft};
}}

.dock-settings {{ min-width: 270px; }}

.dock-settings-row {{ padding: 2px 10px; }}

.dock-settings-row label {{
  color: @dock_fg;
  font-size: 12px;
}}
",
        accent_soft = accent.with_alpha(0.28),
    ));

    // ── user overrides ──────────────────────────────────────────────────────
    let user = config::expand_tilde(&cfg.theme.user_css);
    match std::fs::read_to_string(&user) {
        Ok(text) => {
            s.push_str("\n/* ── user style.css ── */\n");
            s.push_str(&text);
            tracing::debug!(path = %user.display(), "user CSS applied");
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => tracing::warn!(path = %user.display(), error = %e, "cannot read user CSS"),
    }

    s
}
