//! Stylesheet generation.
//!
//! The dock's CSS is produced at runtime from the active Omarchy palette plus
//! the user's config, then handed to a single `GtkCssProvider` that is swapped
//! wholesale on every theme or config change. Swapping one provider (rather
//! than adding more) is what keeps live reload from leaking styles.

use super::{Palette, Rgb};
use crate::config::{self, Config};

/// Build the full stylesheet: palette variables, dock chrome, then user CSS.
pub fn generate(cfg: &Config, palette: &Palette) -> String {
    let mut s = String::with_capacity(4096);

    s.push_str("/* generated by omarchy-dock — do not edit; see style.css */\n");
    s.push_str(&format!(
        "/* theme: {} ({}) */\n",
        palette.name,
        if palette.is_dark() { "dark" } else { "light" }
    ));

    // ── palette variables ───────────────────────────────────────────────────
    // Exposed so user CSS can reference the live theme, e.g. @omarchy_accent.
    let mut names: Vec<_> = palette.iter().collect();
    names.sort_by(|a, b| a.0.cmp(b.0));
    for (name, rgb) in names {
        s.push_str(&format!("@define-color omarchy_{name} {};\n", rgb.to_css()));
    }

    let bg = palette.background();
    let fg = palette.foreground();
    let accent = palette.accent();
    let urgent = palette.urgent();

    // Hairline and shadow have to move in opposite directions depending on
    // whether the panel is dark or light, or one of them vanishes.
    let (hairline, shadow_alpha) = if palette.is_dark() {
        (Rgb { r: 255, g: 255, b: 255 }.with_alpha(0.10), 0.45)
    } else {
        (bg.mix(Rgb { r: 0, g: 0, b: 0 }, 0.35).with_alpha(0.18), 0.20)
    };

    s.push_str(&format!("@define-color dock_bg {};\n", bg.with_alpha(cfg.theme.opacity)));
    s.push_str(&format!("@define-color dock_fg {};\n", fg.to_css()));
    s.push_str(&format!("@define-color dock_accent {};\n", accent.to_css()));
    s.push_str(&format!("@define-color dock_urgent {};\n", urgent.to_css()));

    // ── dock chrome ─────────────────────────────────────────────────────────
    // The layer surface itself must stay fully transparent: Hyprland blurs
    // whatever the surface covers, so a window-level background would be
    // blurred edge-to-edge and the rounded corners would be lost.
    s.push_str(
        "\nwindow, window.background { background: transparent; box-shadow: none; }\n",
    );

    s.push_str(&format!(
        "\n.dock-panel {{
  background-color: @dock_bg;
  border: 1px solid {hairline};
  border-radius: {radius}px;
  box-shadow: 0 8px 28px rgba(0, 0, 0, {shadow_alpha:.2});
}}\n",
        radius = cfg.dock.radius,
    ));

    // Running/urgency indicators and window-count badges.
    s.push_str(&format!(
        "
.dock-indicator {{
  background-color: @dock_accent;
  border-radius: 2px;
  min-width: 5px;
  min-height: 3px;
}}

.dock-indicator.urgent {{ background-color: @dock_urgent; }}

.dock-badge {{
  background-color: @dock_urgent;
  color: {badge_fg};
  border-radius: 9px;
  font-size: 10px;
  font-weight: bold;
  padding: 0 5px;
}}

.dock-label {{
  color: @dock_fg;
  font-size: 12px;
}}
",
        // Badge text must contrast with the urgency colour, not the panel.
        badge_fg = if urgent.luminance() > 0.45 { "#000000" } else { "#ffffff" },
    ));

    // ── user overrides ──────────────────────────────────────────────────────
    let user = config::expand_tilde(&cfg.theme.user_css);
    match std::fs::read_to_string(&user) {
        Ok(text) => {
            s.push_str("\n/* ── user style.css ── */\n");
            s.push_str(&text);
            tracing::debug!(path = %user.display(), "user CSS applied");
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => tracing::warn!(path = %user.display(), error = %e, "cannot read user CSS"),
    }

    s
}
